# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('describe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('cabinet', models.IntegerField()),
                ('room', models.CharField(max_length=64)),
                ('cpu_model', models.CharField(max_length=128)),
                ('cpu_core', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('os', models.CharField(max_length=128)),
                ('product_model', models.CharField(max_length=128)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minions.Business')),
            ],
        ),
    ]
