# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True),
        ),
    ]
