# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0002_auto_20180421_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('detail', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='host',
            old_name='os',
            new_name='OS',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='business_id',
            new_name='business',
        ),
        migrations.AddField(
            model_name='host',
            name='minions_status',
            field=models.CharField(default='undefined', max_length=32),
        ),
        migrations.AlterField(
            model_name='host',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minions.Room'),
        ),
    ]
