# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0004_auto_20180421_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='minions_status',
            field=models.CharField(default='undefined', max_length=32, null=True),
        ),
    ]
